### ISSUE TITLE
Play back rate and Quality control

### ISSUE THREAD

**Issue by Anusha-Gurajapu** [charmy/react-native-youtube-sdk#46]
I would like to control playbackrate and quality of the video as well. Is there a way to do that ? @srfaytkn please do tell me if it is possible through this library. It would be great if we can achieve atleast one of them first

**Comment by ozgursoy** [comment]
It's not possible, Youtube iframe API does not support that features.

**Comment by Anusha-Gurajapu** [comment]
Youtube iframe API does provide playbackRate (speed) control. Please, look into this  @srfaytkn https://developers.google.com/youtube/iframe_api_reference#Playback_rate

**Comment by srfaytkn** [comment]
@Anusha-Gurajapu I don't have time right now to do this additional development, you can help us with sending a pr

**Comment by Anusha-Gurajapu** [comment]
Could you please help me where can I add the respective code @srfaytkn
