### ISSUE TITLE
Playback Rate and Quality

### ISSUE THREAD

**Issue by Anusha-Gurajapu** [charmy/react-native-youtube-sdk#47]
It's not possible, Youtube iframe API does not support that features.

_Originally posted by @ozgursoy in https://github.com/charmy/react-native-youtube-sdk/issues/46#issuecomment-879349840_

Youtube iframe API does provide playbackRate (speed) control. Please, look into this @srfaytkn https://developers.google.com/youtube/iframe_api_reference#Playback_rate

**Comment by srfaytkn** [comment]
duplicate #46
